### ISSUE TITLE
Inappropriate hierarchy for MvxPreferenceFragment

### ISSUE THREAD

**Issue by FatCow8686** [MvvmCross/MvvmCross-AndroidSupport#109]
Hello, I am playing with the preference fragment and have found that the preference fragment should be based on the FullFragging hierarchy rather than the Support Fragging hierarchy. 

From android API reference, the v14 preference fragment has a hierarchy like this:
java.lang.object -> android.app.fragment -> android.support.v14.preference.preferencefragment
which is not from android.support.v4.app.fragment, FullFragging hierarchy should be used.

reference: https://developer.android.com/reference/android/support/v14/preference/PreferenceFragment.html

On the other hand, android has released another support library for preference fragment "PreferenceFragmentCompat" that targets API 7+ device which is inherit from android.support.v4.app.fragment, it would be nice if you guys could add support to this new API. 

reference: 
https://plus.google.com/+AndroidDevelopers/posts/9kZ3SsXdT2T

Thanks =)

**Comment by martijn00** [comment]
I am not sure what you mean. Our current PreferenceFragment is based on the v14 version. 

There is no support for PreferenceFragmentCompat on the moment, so that could be an improvement.

**Comment by FatCow8686** [comment]
Thanks for the response. 

What i mean is that, the immediate parent of the v14 version is android.app.fragment and it is not compatible to android.support.v4.app.fragment. 

If we use v14 version with the support fragging library, it returns an error because it forces the v14 version to convert to android.support.v4.app.fragment.

So, I think the v14 version should be moved under the full fragging hierarchy, correct me if i am wrong, thanks!

**Comment by AlexH83** [comment]
Probably related to this, I've encountered a problem in my own development. I'm using FullFragging and when I try to switch to my MvxPreferenceFragment I'm getting this exception:

11-24 08:31:46.904 I/MonoDroid(16405): UNHANDLED EXCEPTION:
11-24 08:31:46.912 I/MonoDroid(16405): System.ArgumentException: eventSource should be a Fragment
11-24 08:31:46.912 I/MonoDroid(16405): Parameter name: eventSource
11-24 08:31:46.912 I/MonoDroid(16405): at Cirrious.MvvmCross.Droid.Support.Fragging.Fragments.EventSource.MvxBaseFragmentAdapter..ctor (Cirrious.MvvmCross.Droid.Support.Fragging.Fragments.EventSource.IMvxEventSourceFragment) <IL 0x0003f, 0x001e0>
11-24 08:31:46.912 I/MonoDroid(16405): at Cirrious.MvvmCross.Droid.Support.Fragging.Fragments.MvxBindingFragmentAdapter..ctor (Cirrious.MvvmCross.Droid.Support.Fragging.Fragments.EventSource.IMvxEventSourceFragment) <IL 0x00002, 0x00053>
11-24 08:31:46.912 I/MonoDroid(16405): at Cirrious.MvvmCross.Droid.Support.Fragging.Fragments.MvxFragmentExtensions.AddEventListeners (Cirrious.MvvmCross.Droid.Support.Fragging.Fragments.EventSource.IMvxEventSourceFragment) <IL 0x00010, 0x001a3>
11-24 08:31:46.912 I/MonoDroid(16405): at Cirrious.MvvmCross.Droid.Support.Preference.MvxPreferenceFragment..ctor () <IL 0x00009, 0x0008b>
11-24 08:31:46.912 I/MonoDroid(16405): at Nav.Droid.Views.SettingsView..ctor () <IL 0x00001, 0x00023>
11-24 08:31:46.912 I/MonoDroid(16405): at Nav.Droid.Views.HomeView.Show (Cirrious.MvvmCross.ViewModels.MvxViewModelRequest) [0x0009b] in C:\Users\alexh\Documents\Visual Studio 2015\Projects\Nav\Nav\Nav.Droid\Views\HomeView.cs:148
11-24 08:31:46.912 I/MonoDroid(16405): at Nav.Droid.InterfaceImplementations.CustomPresenter.Show (Cirrious.MvvmCross.ViewModels.MvxViewModelRequest) [0x00019] in C:\Users\alexh\Documents\Visual Studio 2015\Projects\Nav\Nav\Nav.Droid\InterfaceImplementations\CustomPresenter.cs:29
11-24 08:31:46.912 I/MonoDroid(16405): at Cirrious.MvvmCross.Droid.Views.MvxAndroidViewDispatcher/<>c__DisplayClass2_0.<ShowViewModel>b__0 () <IL 0x00011, 0x00063>
11-24 08:31:46.927 D/AndroidRuntime(16405): S11-24 08:31:46.912 I/MonoDroid(16405): at Cirrious.MvvmCross.Droid.Views.MvxAndroidMainThreadDispatcher.RequestMainThreadAction (System.Action) <IL 0x0001f, 0x0011f>
11-24 08:31:46.912 I/MonoDroid(16405): at Cirrious.MvvmCross.Droid.Views.MvxAndroidViewDispatcher.ShowViewModel (Cirrious.MvvmCross.ViewModels.MvxViewModelRequest) <IL 0x00021, 0x00173>
11-24 08:31:46.912 I/MonoDroid(16405): at Cirrious.MvvmCross.ViewModels.MvxNavigatingObject.ShowViewModelImpl (System.Type,Cirrious.MvvmCross.ViewModels.IMvxBundle,Cirrious.MvvmCross.ViewModels.IMvxBundle,Cirrious.MvvmCross.ViewModels.MvxRequestedBy) <IL 0x0002e, 0x001c7>
11-24 08:31:46.912 I/MonoDroid(16405): at Cirrious.MvvmCross.ViewModels.MvxNavigatingObject.ShowViewModel (System.Type,Cirrious.MvvmCross.ViewModels.IMvxBundle,Cirrious.MvvmCross.ViewModels.IMvxBundle,Cirrious.MvvmCross.ViewModels.MvxRequestedBy) <IL 0x00006, 0x0006f>
11-24 08:31:46.912 I/MonoDroid(16405): at Cirrious.MvvmCross.ViewModels.MvxNavigatingObject.ShowViewModel (System.Type,System.Collections.Generic.IDictionary`2<string, string>,Cirrious.MvvmCross.ViewModels.IMvxBundle,Cirrious.MvvmCross.ViewModels.MvxRequestedBy) <IL 0x0000b, 0x000af>
11-24 08:31:46.912 I/MonoDroid(16405): at Cirrious.MvvmCross.ViewModels.MvxNavigatingObject.ShowViewModel<Nav.SettingsViewModel> (object,Cirrious.MvvmCross.ViewModels.IMvxBundle,Cirrious.MvvmCross.ViewModels.MvxRequestedBy) <0x0009b>
11-24 08:31:46.912 I/MonoDroid(16405): at Nav.ViewModels.HomeViewModel.ExecuteSelectMenuItemCommand (Nav.ViewModels.FlyoutViewModel) [0x00029] in C:\Users\alexh\Documents\Visual Studio 2015\Projects\Nav\Nav\Nav\ViewModels\HomeViewModel.cs:63
11-24 08:31:46.912 I/MonoDroid(16405): at Cirrious.MvvmCross.ViewModels.MvxCommand`1<Nav.ViewModels.FlyoutViewModel>.Execute (object) <0x000e3>
11-24 08:31:46.912 I/MonoDroid(16405): at Cirrious.MvvmCross.Binding.Droid.Views.MvxListView.ExecuteCommandOnItem (System.Windows.Input.ICommand,int) <IL 0x00021, 0x00187>
11-24 08:31:46.912 I/MonoDroid(16405): at Cirrious.MvvmCross.Binding.Droid.Views.MvxListView.<EnsureItemClickOverloaded>b__17_0 (object,Android.Widget.AdapterView/ItemClickEventArgs) <IL 0x0000d, 0x000a7>
11-24 08:31:46.912 I/MonoDroid(16405): at Android.Widget.AdapterView/IOnItemClickListenerImplementor.OnItemClick (Android.Widget.AdapterView,Android.Views.View,int,long) [0x0000d] in /Users/builder/data/lanes/2185/53fce373/source/monodroid/src/Mono.Android/platforms/android-22/src/generated/Android.Widget.AdapterView.cs:283
11-24 08:31:46.912 I/MonoDroid(16405): at Android.Widget.AdapterView/IOnItemClickListenerInvoker.n_OnItemClick_Landroid_widget_AdapterView_Landroid_view_View_IJ (intptr,intptr,intptr,intptr,int,long) [0x00019] in /Users/builder/data/lanes/2185/53fce373/source/monodroid/src/Mono.Android/platforms/android-22/src/generated/Android.Widget.AdapterView.cs:211
11-24 08:31:46.912 I/MonoDroid(16405): at (wrapper dynamic-method) object.b5c0be5f-65a5-4a54-a8e3-a65bfc504fbb (intptr,intptr,intptr,intptr,int,long) <IL 0x00029, 0x0009b>
11-24 08:31:46.922 W/art     (16405): JNI RegisterNativeMethods: attempt to register 0 native methods for md52ce486a14f4bcd95899665e9d932190b.JavaProxyThrowable
11-24 08:31:46.927 D/AndroidRuntime(16405): Shutting down VM
An unhandled exception occured.

Notice that the IMvxEventSourceFragment is coming from the Fragging library whereas I would expect the preference fragment to be in the FullFragging library, and the FragmentActivity and other fragments are from fullfragging library too.
