### ISSUE TITLE
Error binding MvxRecyclerView

### ISSUE THREAD

**Issue by rsegtx** [MvvmCross/MvvmCross-AndroidSupport#11]
I'm getting an error trying to bind an MvxRecyclerView in my app using the following XML.

```
    <Cirrious.MvvmCross.Droid.Support.RecyclerView.MvxRecyclerView
        android:layout_width="wrap_content"
        android:layout_height="42dp"
        android:layout_weight=".7"
        android:id="@+id/showDateSelectorListView"
        android:scrollbars="horizontal"
        android:scrollbarSize="2dp"
        local:MvxBind="ItemsSource ShowtimeDates; ItemClick ShowtimeDatePicked"
        local:MvxItemTemplate="@layout/showdateitemmvx" />
```

The error I receive is:

MvxBind:Error:  0.69 View type not found - cirrious.mvvmcross.droid.support.recyclerview.MvxRecyclerView

Is there some type of initialization I'm missing? I'm able to use other controls like Mvx.MvxGridView and MvxImageView without any issues.

Thanks for any help.

**Comment by jamie94bc** [comment]
I assume this is because you haven't referenced the assembly in your `Setup.cs` file. Add the following:

``` c#
protected override IList<Assembly> AndroidViewAssemblies {
    get {
        var toReturn = base.AndroidViewAssemblies;
        toReturn.Add(typeof(Cirrious.MvvmCross.Droid.Support.RecyclerView.MvxRecyclerView).Assembly);
        return toReturn;
    }
}
```

**Comment by rsegtx** [comment]
Thanks much Jamie. I thought I had tried that but apparently not because its working now. Thanks again for the help!
