### ISSUE TITLE
Fragment Cache logic is multiplied - in Support.Fragging and Support.AppCompat

### ISSUE THREAD

**Issue by thefex** [MvvmCross/MvvmCross-AndroidSupport#111]
Both MvxCachingFragmentCompatActivity and MvxCachingFragmentActivity do the same thing - but the code is copy-pasted because of interface mis-match.

Supporting two code-lines (which do exactly the same thing) is unacceptable. 
Do not pick this issue as I am refactoring this now. In fifteen minutes I should commit working solution to the problem.

**Comment by thefex** [comment]
working at issue
https://github.com/thefex/MvvmCross-AndroidSupport/commit/373fc4f1b86be2ee8a33ea93e9a03c84e42ed9c0
when I test that I will make pull request

**Comment by martijn00** [comment]
Did you know this class exists in full fragging too: https://github.com/MvvmCross/MvvmCross/blob/4.0/Cirrious/Cirrious.MvvmCross.Droid.FullFragging/MvxCachingFragmentActivity.cs

**Comment by thefex** [comment]
thanks, didn't know that, going to fix that too

**Comment by vvolkgang** [comment]
@martijn00 didn't notice FullFragging also had that, it still has the previous implementation. @thefex keep that in mind.

**Comment by martijn00** [comment]
Ok, so the new implementation of @vvolkgang also needs to be copied over to full fragging.

**Comment by vvolkgang** [comment]
@thefex could create a `Shared Project` with that `MvxActivityCachingProcessor` base implementation. Either libs could coexist without direct dependencies.

**Comment by martijn00** [comment]
Don't know if a shared project is a good idea. We already have a lot of projects with code on different places.

**Comment by vvolkgang** [comment]
Other cases similar to this? We need to figure out something then, this Is
too error prone. @cheesebaron suggested Fody right? Has anyone went into it?
On Mon, 9 Nov 2015 at 11:51, Martijn van Dijk notifications@github.com
wrote:

> Don't know if a shared project is a good idea. We already have a lot of
> projects with code on different places.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MvvmCross/MvvmCross-AndroidSupport/issues/111#issuecomment-155042279
> .
> 
> ## 
> 
> Regards,

Álison Fernandes

**Comment by thefex** [comment]
We might ask to get free PostSharp license for a project instead of Fody btw.

**Comment by vvolkgang** [comment]
Is there something in PostSharp you know that can solve this?
On Mon, 9 Nov 2015 at 16:04, Przemysław Raciborski notifications@github.com
wrote:

> We might ask to get free PostSharp license for a project instead of Fody
> btw.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MvvmCross/MvvmCross-AndroidSupport/issues/111#issuecomment-155106609
> .
> 
> ## 
> 
> Regards,

Álison Fernandes

**Comment by thefex** [comment]
I am not a Fody expert - but from what I have seen it is pretty complicated to write custom weavings. 
Using PostSharp we could create compile-time validated CacheFragmentActivityAspect (really easy, just implement one interface) which would add whole caching logic to Activity.

Then we would just create few "stub" classes:
[CacheFragmentActivityAspect]
public class MvxCachingAppCompatActivity : MvxAppCompatActivity { }

[CacheFragmentActivityAspect]
public class MvxCachingFragmentActivity : MvxFragmentActivity { }

and so on..

but well all of the solutions boil down to creating shared project.

I have another idea which I think is worth checking:
How about we abstract FragmentManager into some kind of interface (let say IFragmentManager), expose it in main MvvmCross library and then write all the logic in MvvmCross main library? We would avoid in creating just-one-new-library. At this moment the only thing which stop us from doing that is: Android.App.FragmentManager and support.v4.FragmentManager interface mis-match.

I will investigate it further this week, I should find some free-time after work.

**Comment by martijn00** [comment]
Lots have been moved over to the `MvvmCross.Droid.Shared` library. Please continue in there if more stuff can be moved, or improved.
