### ISSUE TITLE
 Exception is thrown when fragment is shown by ShowFragment method

### ISSUE THREAD

**Issue by thefex** [MvvmCross/MvvmCross-AndroidSupport#142]
ShowFragment is broken after new auto-registration cache logic.

**Comment by martijn00** [comment]
This is fixed with the presenter changes, right?

**Comment by ghost** [comment]
I'm not sure if this is related to this issue but using beta8 and the MvxFragement attribute (from FullFragging), I get a crash about cannot find the activity. I am using MvxAppCompactActivity.
 When I switched to the support attribute instead it worked. My project is based on the sample xplatform.menus
