### ISSUE TITLE
Adding app compat removing Cirrious.MvvmCross.Binding.Droid

### ISSUE THREAD

**Issue by dot-ly** [MvvmCross/MvvmCross-AndroidSupport#143]
Before i install MVVM Appcompat packages via the nuget pre release channel, my code builds fine. 

after i add the appcompat packages, its removing Cirrious.MvvmCross.Binding.Droid  (before and after images attached).

before adding app compat (just standard mvvmcross starter ) 
![screen shot 2015-12-10 at 16 41 07](https://cloud.githubusercontent.com/assets/5125127/11721830/abc88824-9f5d-11e5-9a01-4e645d2aa751.png)
after adding app compat libs 
![screen shot 2015-12-10 at 16 44 29](https://cloud.githubusercontent.com/assets/5125127/11721833/aed78eb6-9f5d-11e5-89ea-54ec6aa30ad1.png)

any ideas? these are the two build errors im getting

![screen shot 2015-12-10 at 16 48 53](https://cloud.githubusercontent.com/assets/5125127/11721922/1c21789c-9f5e-11e5-9e6a-91274cf83596.png)

Views/LoginView.cs(20,27): error CS0012: The type `Cirrious.MvvmCross.Binding.Droid.Views.IMvxLayoutInflaterHolder' is defined in an assembly that is not referenced. Consider adding a reference to assembly`Cirrious.MvvmCross.Binding.Droid, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null'

Views/LoginView.cs(20,27): error CS0012: The type `Cirrious.MvvmCross.Binding.BindingContext.IMvxBindingContextOwner' is defined in an assembly that is not referenced. Consider adding a reference to assembly`Cirrious.MvvmCross.Binding, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null'

**Comment by Cheesebaron** [comment]
You didn't add the package containing Binding

**Comment by dot-ly** [comment]
which package is that? it was there before i added the appcompat packages. i think the mvvmcross core adds it? do i need to re-add mvvmcross core?

**Comment by Cheesebaron** [comment]
I don't see it in the list in the first post. Binding have been moved out into its own package. So you have probably updated some of your old packages when installing appcompat stuff.

https://www.nuget.org/packages/MvvmCross.HotTuna.Binding/4.0.0-beta7

**Comment by dot-ly** [comment]
yep that's it! i added mvvmcross binding, and removed the MvxBindingAttributes.xml from android. getting this error now 
![screen shot 2015-12-10 at 17 08 25](https://cloud.githubusercontent.com/assets/5125127/11722513/faa677a0-9f60-11e5-8446-d377ffb34a87.png)

![screen shot 2015-12-10 at 17 40 56](https://cloud.githubusercontent.com/assets/5125127/11723240/38234226-9f65-11e5-8bac-710e4f7fd629.png)

**Comment by dot-ly** [comment]
Ok fixed this by updating MvvmCross on my Core project! dam all those packages get confusing! sorry about this! and thanks for the help
