### ISSUE TITLE
Custom RecyclerView adapter overrided by existing one

### ISSUE THREAD

**Issue by jbolle** [MvvmCross/MvvmCross-AndroidSupport#15]
Hi guys,

I have some difficulties to use my own RecyclerView adapter. The properties of my custom adapter are overrided in the Adapter setter in MvxRecyclerView.cs because in the sample code below, "existing" is never null because of the first adapter instantiated in the MvxRecyclerView constructor.

**_MvxRecyclerView.cs_**

```
if (value != null && existing != null)
{
     value.ItemsSource = existing.ItemsSource;
     value.ItemTemplateId = existing.ItemTemplateId;
     value.ItemClick = existing.ItemClick;
     value.ItemLongClick = existing.ItemLongClick;

     SwapAdapter((Adapter)value, false);
 }
```

And this is my code:

 **_view.axml_**

```
<Cirrious.MvvmCross.Droid.Support.RecyclerView.MvxRecyclerView
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:local="http://schemas.android.com/apk/res-auto"
    android:id="@+id/date_filter"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_marginTop="10dp"
    android:layout_marginBottom="15dp"
    local:MvxBind="Visible NotLoading"
    local:MvxItemTemplate="@layout/date_filter_item" />
```

**_myAdapter.cs_**

```
public class myAdapter : MvxRecyclerAdapter
{
    public myAdapter (IEnumerable itemsSource)
    {
        this.ItemsSource = itemsSource;
    }
}
```

**Setting adapter in _myView.cs_**

```
_dateFilterRecyclerView = view.FindViewById<MvxRecyclerView>(Resource.Id.date_filter);
_dateFilterRecyclerView.Adapter = new myAdapter(myViewModel.DateFilterItems);
```

Did I miss something in my implementation? Or can I make this differently?

Thanks for your help and your work! ;)

**Comment by jamie94bc** [comment]
It's a binding adapter - you should be binding `ItemsSource` rather than setting it in your adapter...

``` XML
local:MvxBind="ItemsSource DateFilterItems;Visible NotLoading"
```

If you have a static collection, use the standard `RecyclerView` and inherit from `Android.Support.V7.Widget.RecyclerView.Adapter`.
