### ISSUE TITLE
Error on new Beta 8 AppCompat/MvxAppCompatActivity.cs

### ISSUE THREAD

**Issue by SergioZgz** [MvvmCross/MvvmCross-AndroidSupport#164]
Hi :) 

You forgot add 
using Android.Views;
using Android.Util; 
to MvvmCross.Droid.Support.V7.AppCompat/MvxAppCompatActivity.cs

And this make an error on public override View OnCreateView

I cannot fix it here to make a pull request sorry. (I cannot install anything in this computer sorry)

**Comment by Cheesebaron** [comment]
I actually added it on my laptop at work will commit tomorrow :)

**Comment by SergioZgz** [comment]
Perfect :) and Thanks for your work :)

Wow Cheesebaron reply me :) :) :)

**Comment by SergioZgz** [comment]
Fixed :) thx and close
