### ISSUE TITLE
MvxAppCompatSpinner needs to support android:prompt

### ISSUE THREAD

**Issue by ghost** [MvvmCross/MvvmCross-AndroidSupport#169]
The spinner currently does not support the floating label style found in the native spinner control.

**Comment by martijn00** [comment]
Can you make a PR to add that functionality?

**Comment by ghost** [comment]
@martijn00 I would like to, but it would be a few weeks before I had the time. It seems simple to do though.

**Comment by ghost** [comment]
Can use this for reference: https://github.com/ganfra/MaterialSpinner/blob/master/library/src/main/java/fr/ganfra/materialspinner/MaterialSpinner.java

**Comment by Dexyon** [comment]
@robertbaker Looks like this library is a custom library which implements the floating label. I can't find any reference to the floating label on a spinner myself. Do you know if it is native supported by Android via a support library? Then we would prefer a link to that as well.

**Comment by ghost** [comment]
@Dexyon I believe you are correct. It's not a native feature :(. You would think android would...

The google contacts app uses a placeholder for the dropdown.
