### ISSUE TITLE
MvxActivityCompat/MvxCachingFragmentActivityCompat InvalidateOptionsMenu should override the base method

### ISSUE THREAD

**Issue by kjeremy** [MvvmCross/MvvmCross-AndroidSupport#17]
Currently these classes don't override the base method.  They probably should.

**Comment by Cheesebaron** [comment]
> don't override the base method

que?

Elaborate, please?

**Comment by kjeremy** [comment]
MvxActivityCompat:

``` csharp
        public void InvalidateOptionsMenu()
        {
            CompatDelegate.InvalidateOptionsMenu();
        }
```

That should be `public override void InvalidateOptionsMenu()``` otherwise the method won't get called.

**Comment by Cheesebaron** [comment]
Care to make a PR, so this can make it into my planned nuget release tomorrow?

**Comment by kjeremy** [comment]
I think I'm going to hold off... I'm not sure if I'm correct or not based on some other examples out there.  It looks like this method will never get called to me.

**Comment by martijn00** [comment]
As shown in the example of google we shouldn't override it: https://github.com/android/platform_development/blob/master/samples/Support7Demos/src/com/example/android/supportv7/app/AppCompatPreferenceActivity.java
