### ISSUE TITLE
Exception is thrown when navigating back with a back stack

### ISSUE THREAD

**Issue by vecalion** [MvvmCross/MvvmCross-AndroidSupport#170]
The issue is related to navigating back and forth to a ViewModel that takes different init params and requires a fragment to be added to a back stack.

`A -> B (init 'some = 1') -> A -> B (init 'some = 2') -> A` (Exception occurs here where trying to navigate back to fragment A).

Here is a demo project:
https://github.com/vecalion/MvvmCross-AndroidSupport

The issue is in the ShowFragment method of MvxCachingFragmentCompatActivity.
https://github.com/MvvmCross/MvvmCross-AndroidSupport/blob/d27276cc4f613f3d6bdce20dc8d7828290eebd9c/MvvmCross.Droid.Support.V7.AppCompat/MvxCachingFragmentCompatActivity.cs#L230

When `fragmentReplaceMode == FragmentReplaceMode.ReplaceFragmentAndViewModel`, the method makes two actions:
1) `ft.Remove(fragInfo.CachedFragment);`
2) `ft.Replace(fragInfo.ContentId, fragInfo.CachedFragment, fragInfo.Tag);`

According to the documentation, android will add both these actions to the backstack:

_If you add multiple changes to the transaction (such as another `add()` or `remove()`) and call `addToBackStack()`, then all changes applied before you call `commit()` are added to the back stack as a single transaction and the Back button will reverse them all together._

So when navigating back from B to A, the system recreates Fragment B by it's own, which causes the issue.

As possible solution:
`ft.Remove(fragInfo.CachedFragment);` can be simple removed, since `Replace()` method does `Remove()` and `Add()` internally and there is no need to additionally call `Remove()`

_Replace an existing fragment that was added to a container. This is essentially the same as calling `remove(Fragment)` for all currently added fragments that were added with the same containerViewId and then `add(int, Fragment, String)` with the same arguments given here._

If though there is a reason to call `Remove()` it can be done in a separate transaction which is not added to the back stack.

**Comment by Relaxguy** [comment]
I'm getting the same issue, basically using the param to open a new fragment based on a list click.

Show A -> Show B (1) -> Back pressed (A is showing) -> Show B (3) -> Back pressed (A should be shown) - Exception thrown

If you Override `UniqueImmutableCacheTag` in the offending fragment no exception will be thrown, instead more and more copies of the fragment will get added to the backstack.

**Comment by vecalion** [comment]
@Relaxguy, yep, that was the first suggestion by @martijn00 - to override `UniqueImmutableCacheTag`. However it causes other issues, like having `OnCreateOptionsMenu` method on a fragment called multiple times and stacking unnecessary fragments in memory.

I resolved the issue by deleting the following line:
`ft.Remove(fragInfo.CachedFragment);`

https://github.com/MvvmCross/MvvmCross-AndroidSupport/blob/d27276cc4f613f3d6bdce20dc8d7828290eebd9c/MvvmCross.Droid.Support.V7.AppCompat/MvxCachingFragmentCompatActivity.cs#L230
