### ISSUE TITLE
ItemSelected is not binding on MvxAppCompatSpinner

### ISSUE THREAD

**Issue by ghost** [MvvmCross/MvvmCross-AndroidSupport#171]
ItemSelected is not being bound. The exact same layout and code work for the non-appcompat version of MvxSpinner. Must be a bug in MvxAppCompatSpinnerSelectedItemBinding

**Comment by ghost** [comment]
I'm uncertain of the cause, I did a diff on the 2 widgets and the binding classes, everything is the same.

**Comment by vvolkgang** [comment]
In your `Setup.cs`

``` csharp
        protected override void FillTargetFactories(IMvxTargetBindingFactoryRegistry registry)
        {
            MvxAppCompatSetupHelper.FillTargetFactories(registry);
            base.FillTargetFactories(registry);
        }
```

**Comment by ghost** [comment]
@vvolkgang thanks, I was making a new registery in my setup constructor, which was wrong.
