### ISSUE TITLE
Recyle View Class not found exception

### ISSUE THREAD

**Issue by dot-ly** [MvvmCross/MvvmCross-AndroidSupport#177]
Having an issue using MvxRecyleView  in an activity , getting the following error 

![screen shot 2016-01-27 at 18 58 56](https://cloud.githubusercontent.com/assets/5125127/12624894/3e16e6da-c529-11e5-8684-57c483c70c95.png)

![screen shot 2016-01-27 at 18 58 01](https://cloud.githubusercontent.com/assets/5125127/12624904/4898e4d2-c529-11e5-837d-a3076aea8ab1.png)

This is how i'm referencing it in my axml 

![screen shot 2016-01-27 at 19 10 58](https://cloud.githubusercontent.com/assets/5125127/12625023/cd67d9c0-c529-11e5-9a76-45736cd5dcdd.png)

**Comment by dot-ly** [comment]
Had to use   

`<MvvmCross.Droid.Support.V7.RecyclerView.MvxRecyclerView/> not just   <MvxRecyclerView>`

**Comment by ghost** [comment]
I think this is a valid issue...

The inflater should inflate to the appcompat controls automatically.

**Comment by dot-ly** [comment]
Ok, reopened for the guys to review. Cheers

**Comment by ghost** [comment]
Looks like https://github.com/MvvmCross/MvvmCross-AndroidSupport/blob/master/MvvmCross.Droid.Support.V7.AppCompat/MvxAppCompatActivityHelper.cs

is not getting called (at least when I navigate to a fragment that has Mvx.Spinner.

**Comment by ghost** [comment]
@AhmedWarreth Are you using 4.0.0.beta8?

If you are, I would like you to test a fix.

**Comment by dot-ly** [comment]
I am! sure thing

**Comment by ghost** [comment]
hmm actually, you should be unaffected by the issue I referenced.

Do you have this in your Droid project's Setup.cs

```
        protected override IEnumerable<Assembly> AndroidViewAssemblies
            =>
                new List<Assembly>(base.AndroidViewAssemblies)
                    {
                        typeof(NavigationView).Assembly,
                        typeof(FloatingActionButton).Assembly,
                        typeof(Toolbar).Assembly,
                        typeof(DrawerLayout).Assembly,
                        typeof(ViewPager).Assembly,
                        typeof(MvxRecyclerView).Assembly,
                        typeof(MvxAppCompatSpinner).Assembly
                    };
```

**Comment by dot-ly** [comment]
I have this 

`protected override IEnumerable<Assembly> AndroidViewAssemblies => new List<Assembly>(base.AndroidViewAssemblies)
        {
            typeof(Android.Support.Design.Widget.NavigationView).Assembly,
            typeof(Android.Support.Design.Widget.FloatingActionButton).Assembly,
            typeof(Android.Support.V7.Widget.Toolbar).Assembly,
            typeof(Android.Support.V4.Widget.DrawerLayout).Assembly,
            typeof(Android.Support.V4.View.ViewPager).Assembly,
            typeof(MvvmCross.Droid.Support.V7.RecyclerView.MvxRecyclerView).Assembly
        };
`

**Comment by ghost** [comment]
@AhmedWarreth please close I originally misunderstood this issue. Since you are doing FindByViewId, that would be correct since the recycler view is the appcompat version.
