### ISSUE TITLE
Crash in Support Example

### ISSUE THREAD

**Issue by Ryan-Palmer** [MvvmCross/MvvmCross-AndroidSupport#184]
If you page around the pager adapters and navigate around the app for just a minute or so, you get a null ref exception on line 158 of MvxfragmentPagerAdapter2.
This is :
var f = _fragmentManager.GetFragment(bundle, key);
and the exception is:
Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference

**Comment by vecalion** [comment]
I created a bit more descriptive issue with a sample project and detailed steps how to reproduce the exception: https://github.com/MvvmCross/MvvmCross-AndroidSupport/issues/229
