### ISSUE TITLE
After updating MvvmCross V4 - app is getting crash on SplashScreen (MvxSplashScreenActivity)  

### ISSUE THREAD

**Issue by sujeetulli** [MvvmCross/MvvmCross-AndroidSupport#185]
"Could not load type 'Android.OS.BaseBundle' from assembly 'Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'."

protected override void OnCreate (Android.OS.Bundle bundle)
{
       //Error bundle is getting null
    base.OnCreate (bundle);
}

To help us fix your issue, please provide the information in the below template. 

> Note: There is often little we can do without a minimal reproducible sample of the issue, so please provide that in a standalone github repository and link it here.
### Steps to reproduce

1.

2.

3.
### Expected behavior

Tell us what should happen
### Actual behavior

Tell us what happens instead
### Configuration

**Version:** 4.0.0

**Comment by Cheesebaron** [comment]
I've marked this as invalid, please fill out the template.

**Comment by sujeetulli** [comment]
Hi Cheesebaron, Thanks for your quick response, I have fixed this issue form our end not in core..

I have referred the below link.
http://stackoverflow.com/questions/31488166/could-not-load-type-android-os-basebundle

WR
SU
