### ISSUE TITLE
Preferences has multiple dependencies which shouldn't be required

### ISSUE THREAD

**Issue by vvolkgang** [MvvmCross/MvvmCross-AndroidSupport#187]
MvvmCross.Droid.Support.V14.Preference currently depends on multiple libs which might not be required. Namely:
- Fragging 
- AppCompat
- RecyclerView

![example](https://i.gyazo.com/06c6160b93e4a3dc5228c98248b6a2c3.png)

**Comment by Dexyon** [comment]
You mean our own MvvmCross libraries? Or the Xamarin libraries. 
When you look at NuGet V14 Pref requires the following:
Dependencies

Xamarin.Android.Support.v4 (= 23.1.1)
Xamarin.Android.Support.v7.RecyclerView (= 23.1.1)
Xamarin.Android.Support.v7.AppCompat (= 23.1.1)
Xamarin.Android.Support.v7.Preference (= 23.1.1)

**Comment by martijn00** [comment]
Fixed by: https://github.com/MvvmCross/MvvmCross-AndroidSupport/commit/1a6a952b830f70fa453f078bea38fb7de4541699
