### ISSUE TITLE
Fragment Navigation issue

### ISSUE THREAD

**Issue by nicolgit** [MvvmCross/MvvmCross-AndroidSupport#192]
Probably there is an problem in navigating fragments with MvvmCross 4. The issue is viewable also on droid sample support.

**Sequence 1**
(1) open app
(2) tap on menu - compose message (activity) 
(3) press android back button
(4) home page is shown (OK)

**Sequence 2**
(1) open app
(2) tap on menu - settings (fragment)
(3) press android back button
(4) app exits 
My expectation is that _fragment navigation supports back button_. Is there something that I missed or is this a MvvmCross bug?

**Comment by nmilcoff** [comment]
Actually MvvmCross supports fragment navigation. Just add the parameter "addToBackStack: true" in this line: 

https://github.com/MvvmCross/MvvmCross-AndroidSupport/blob/master/Samples/Example.Droid/Activities/Caching/MainActivityFragmentCacheInfoFactory.cs#L44

And the fragment transaction will be added to BackStack.

**Comment by nicolgit** [comment]
It works, thank you!
