### ISSUE TITLE
Navigation issue (?)

### ISSUE THREAD

**Issue by nicolgit** [MvvmCross/MvvmCross-AndroidSupport#193]
I'm new to Android programming so I'm not sure if this is correct but I'd like to implement this sequence:

(1) start a fragment (home page)
(2) go to an activity (I need to show a full screen page)
(3) show another fragment activity

In the attached sample I have added a button on MessageActivity that jumps to ExampleRecyclerViewModel.

this is the sequence:
(1) start application
(2) open compose message activity (from menu)
(3) tap on "click me" button (" ShowViewModel<ExampleRecyclerViewModel> ();")
(4) Instead to show ExampleRecyclerViewModel an exception is raised

_"ava.Lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.ArrayList.set(int, java.lang.Object)' on a null object reference"
_

Is this my misunderstanding or a bug?
How can obtain this behavior?

thank you!

[MvvmCross-AndroidSupport-master.zip](https://github.com/MvvmCross/MvvmCross-AndroidSupport/files/170356/MvvmCross-AndroidSupport-master.zip)

**Comment by Cheesebaron** [comment]
Please use the issue template and provide a minimum reproducible sample.

**Comment by nicolgit** [comment]
Hi @Cheesebaron , thank you for your reply!
The minimum reproducible sample is the link included in my first message.

in order to repro the issue:

 (1) start application (example.droid)
 (2) open compose message activity (from hamburger menu=
 (3) tap on "click me" button (" ShowViewModel ();")
 (4) Instead to show ExampleRecyclerViewModel an exception is raised

please let me know if you need any further information,

**Comment by Cheesebaron** [comment]
If you read the issue template that you disregarded entirely we write:

> please provide that in a standalone github repository and link it here.

No zip files please.

**Comment by nicolgit** [comment]
yes, [MEA CULPA](https://en.wikipedia.org/wiki/Mea_culpa) I didn't read it:-)

Ok, I'm doing asap
Thank you!
N

**Comment by nicolgit** [comment]
Here the git repository:
[https://github.com/NicolaDelfino/NicolGit-Tmp-01](https://github.com/NicolaDelfino/NicolGit-Tmp-01)
