### ISSUE TITLE
MvxSpinner binding issue

### ISSUE THREAD

**Issue by nicolgit** [MvvmCross/MvvmCross-AndroidSupport#201]
Stand alone Git Repository: https://github.com/NicolaDelfino/NicolGit-Tmp-01.git
### Steps to reproduce
1. start the app
2. on the app start page you can see:
- Use the menu to browse...
- aaaa1
- aaaa2
- lorem ipsut dixit
1. on visual studio output window there is the following message:

`MvxBind:Warning: 0.89 Failed to create target binding for binding SelectedItem for SelectedLanguage`
`03-26 18:16:54.227 I/mono-stdout( 6918): MvxBind:Warning:  0.89 Failed to create target binding for binding SelectedItem for SelectedLanguage`
`[0:] MvxBind:Warning:  0.89 Failed to create target binding for binding SelectedItem for SelectedLanguage`
### Expected behavior

on the app start page I should see:
- use the menu to browse...
- aaaa2
- aaaa2
- lorem ipsut dixit
### Actual behavior

MvxSpinner binding on SelectedItem is not working
### Configuration

**Version:** 4.0.0

**Comment by smulrich** [comment]
I am having the same issue.  I implemented according to the API examples:

https://github.com/MvvmCross/MvvmCross-Tutorials/blob/master/ApiExamples/ApiExamples.Core/ViewModels/ViewModels.cs

https://github.com/MvvmCross/MvvmCross-Tutorials/blob/master/ApiExamples/ApiExamples.Droid/Resources/Layout/Test_Spinner.axml

List is populated but binding to SelectedItem is not working.

**Comment by ghost** [comment]
You guys are missing this in your droid setup.cs

```
        protected override void FillTargetFactories(IMvxTargetBindingFactoryRegistry registry)
        {
            base.FillTargetFactories(registry);
            MvxAppCompatSetupHelper.FillTargetFactories(registry);
        }

```

**Comment by martijn00** [comment]
Add the override to your setup and it will work.

**Comment by ErgilV** [comment]
In the github sample there is no code as per martijn00's comment. I fail to understand as well from what library the MvxAppCompatSetupHelper is comming. Could someone try explain the solution mentioned above?

**Comment by kjeremy** [comment]
https://github.com/MvvmCross/MvvmCross-AndroidSupport/search?utf8=%E2%9C%93&q=MvxAppCompatSetupHelper
