### ISSUE TITLE
AppCompatDialogFragment (v7) vs DialogFragment (v4)

### ISSUE THREAD

**Issue by IlSocio** [MvvmCross/MvvmCross-AndroidSupport#209]
I think that both the:
- MvxEventSourceDialogFragment
  https://github.com/MvvmCross/MvvmCross-AndroidSupport/blob/master/MvvmCross.Droid.Support.V7.Fragging/Fragments/EventSource/MvxEventSourceDialogFragment.cs
- MvxDialogFragment
  https://github.com/MvvmCross/MvvmCross-AndroidSupport/blob/master/MvvmCross.Droid.Support.V7.Fragging/Fragments/MvxDialogFragment.cs

should be moved to the MvvmCross.Droid.Support.V4 namespace, because these classes are based on DialogFragment (v4)

And two different classes should be added under the MvvmCross.Droid.Support.V7.AppCompat namespace... (or maybe under MvvmCross.Droid.Support.V7.Fragging?)
- MvxEventSourceAppCompatDialogFragment
- MvxAppCompatDialogFragment

which will be based on AppCompatDialogFragment (v7)
http://developer.android.com/intl/zh-cn/reference/android/support/v7/app/AppCompatDialogFragment.html

Is it right?

**Comment by martijn00** [comment]
It seems you are right! Could you make a PR to fix this? The `MvxAppCompatDialogFragment` should go under the `AppCompat` library.

**Comment by IlSocio** [comment]
Actually, is the MvvmCross.Droid.Support.V7.Fragging namespace really needed?
It seems to be inconsistent against the naming convention of the official support library...

**Comment by IlSocio** [comment]
Sure Martin, I'll try to create a PR ;)

**Comment by martijn00** [comment]
It might not be needed. I think we introduced it to separate the whole fragment thing a while ago. Maybe we should refactor this and put it into the official structure? What does @Cheesebaron think?

**Comment by Cheesebaron** [comment]
So yes.
- [x] Move MvxDialogFragment to v4 (based on [`Android.Support.v4.App.DialogFragment`](http://developer.android.com/intl/zh-cn/reference/android/support/v4/app/DialogFragment.html))
- [x] Make new MvxAppCompatDialogFragment in v7.Fragging (based on [`Android.Support.v7.App.AppCompatDialogFragment`](http://developer.android.com/intl/zh-cn/reference/android/support/v7/app/AppCompatDialogFragment.html))

**Comment by IlSocio** [comment]
Since the MvxAppCompatDialogFragment will be strictly dependent from the AppCompat, wouldn't it better to place it under the v7.AppCompat namespace?

By placing it under the v7.Fragging we'll introduce a new nuget dependency and people who installs the v7.Fragging package will be forced to install the v7.AppCompat package too.

**Comment by IlSocio** [comment]
I've just submitted a PR for moving all the V4 classes to the proper namespace.
I'll submit a different PR for the MvxAppCompatDialogFragment.

**Comment by martijn00** [comment]
I've merged this through #214 Please check if everything works as you would expect.

**Comment by IlSocio** [comment]
I checked and it's perfect Martijn! ;)
