### ISSUE TITLE
MvxSplashScreenCompatActivity should not exist (or not depend on MvxAppCompatActivity)

### ISSUE THREAD

**Issue by kjeremy** [MvvmCross/MvvmCross-AndroidSupport#227]
The splash screen has to be divorced from Mvx.  It's a special activity that makes assumptions about the state of Mvx. `MvxSplashScreen` inherits from `MvxAppCompatActivity` which violates these assumptions.  Either `MvxSplashSCreenCompatActivity` needs to die or it needs to inherit from `AppCompatActivity`.

**Comment by thefex** [comment]
+1 for killing MvxSplashScreen
