### ISSUE TITLE
Crash when using custom MvxRecyclerAdapter with version 4.1.4 of V7.RecyclerView

### ISSUE THREAD

**Issue by modplug** [MvvmCross/MvvmCross-AndroidSupport#239]
### Steps to reproduce
1. Create a custom MvxRecyclerAdapter

2.Upgrade MvvmCross.Droid.Support.V7.RecyclerView from 4.1.0 to 4.1.4
1. It crashes when trying to binding inflate due to ItemTemplateId being 0

Old code that stopped working:
`protected override View InflateViewForHolder(ViewGroup parent, int viewType, IMvxAndroidBindingContext bindingContext)
{
       var view = bindingContext.BindingInflate(this.ItemTemplateId, parent, false);
}
`
New code that fixes the issue:
`protected override View InflateViewForHolder(ViewGroup parent, int viewType,
            IMvxAndroidBindingContext bindingContext)
        {
            var view = bindingContext.BindingInflate(ItemTemplateSelector.GetItemLayoutId(viewType), parent, false);
        }`
**Version:** 4.1.4

**Comment by martijn00** [comment]
You need to use the new ItemTemplateSelector to make this work.
