### ISSUE TITLE
OMG do we even need all of these annoying AppCompat Target Bindings?

### ISSUE THREAD

**Issue by kjeremy** [MvvmCross/MvvmCross-AndroidSupport#262]
Since `AppCompatImageView` extends `ImageView` do we even need these target bindings?

**Comment by Cheesebaron** [comment]
Most likely we don't need a lot of them.

**Comment by ghost** [comment]
@kjeremy that was my goof.

**Comment by Cheesebaron** [comment]
Unless we want to add AppCompat specific target bindings, they are not needed for the most part, unless the class it inherits from isn't one of the original bindings.
