### ISSUE TITLE
App breaks when using MvxAppCompatActivity and res/transition folder

### ISSUE THREAD

**Issue by eugenioestrada** [MvvmCross/MvvmCross-AndroidSupport#272]
You can reproduce this issue using the Examples project, you only have to import the Resources/transition folder in the repository and run the examples app.

You'll get an exception in the SetContentView of MvxAppCompatActivity class.

I didn't figure why this is happening....

**Comment by kjeremy** [comment]
Which version of the support libs are you using?

**Comment by eugenioestrada** [comment]
Design, V4, V7.AppCompat, V7.RecyclerView. As I said the bug I found in my app it also occurs in the Samples https://github.com/MvvmCross/MvvmCross-AndroidSupport/tree/master/Samples

To reproduce it you only have to add the transition folder in the Android Resources and create a new xml transition file. For example following the android documentation:

https://developer.android.com/reference/android/transition/Transition.html

**Comment by kjeremy** [comment]
Is this a regression from a previous mvvmcross version?

**Comment by eugenioestrada** [comment]
No, I've installed the latest mvvmcross version from nuget this weekend it's a clean installation

**Comment by eugenioestrada** [comment]
You can se the trace and the build log here: https://gist.github.com/eugenioestrada/ba5b17df140544c4f0849da3f82e6bc5

**Comment by eugenioestrada** [comment]
Fixed suffixing -v21 to the transitions folder

**Comment by kjeremy** [comment]
Sweet.  Please close.
