### ISSUE TITLE
MvvmCross.Droid.Support.V7.AppCompat nuspec dependencies does not match package.config dependencies

### ISSUE THREAD

**Issue by ggirard07** [MvvmCross/MvvmCross-AndroidSupport#276]
### Steps to reproduce
1. Create a new Android project
2. Install the MvvmCross.Droid.Support.V7.AppCompat NuGet
3. Pay attention to dependencies listed in the NuGet confirmation window
### Expected behavior

Dependencies required by the package should be based on what NuGets the project is actually using.
(defined in the project `packages.config` [here](https://github.com/MvvmCross/MvvmCross-AndroidSupport/blob/master/MvvmCross.Droid.Support.V7.AppCompat/packages.config)).
### Actual behavior

MvvmCross.Droid.Support.V7.AppCompat is currently requiring dependencies which look no longer used (`MvvmCross.Plugin.Json`, `MvvmCross.Droid.Support.V4`, ...) whereas some NuGet actually really used are not listed as dependencies (`MvvmCross.Binding`, `Xamarin.Android.Support.Vector.Drawable`, ...).
### Configuration

**Version:** 4.2.0

**Comment by Cheesebaron** [comment]
Added binding and removed json. Vector Drawable should be removed from the project as it doesn't seem like it is being used anywhere, so that is a false positive. Thanks for the report.
