### ISSUE TITLE
Doubts about MvxCachingFragment...Adapter

### ISSUE THREAD

**Issue by IlSocio** [MvvmCross/MvvmCross-AndroidSupport#299]
Hi all, 
I just noticed that the two classes below have been marked as obsolete / deprecated

```
public class MvxFragmentPagerAdapter : FragmentPagerAdapter
public class MvxFragmentStatePagerAdapter : FragmentStatePagerAdapter
```

and have been replaced with the two classes below:

```
public abstract class MvxCachingFragmentPagerAdapter : PagerAdapter
public class MvxCachingFragmentStatePagerAdapter : MvxCachingFragmentPagerAdapter 
```

and I have a couple of concerns:
- the base class has been changed, and now, both the MvxCaching\* classes inherit from the PagerAdaper base-class. Is this change intentional? or they should still inherit from FragmentPagerAdapter / FragmentStatePagerAdapter? 
- in case that the derivation is correct, the name of the MvxCaching\* classes is misleading, because they ends with "FragmentPagerAdapter", despite they don't inherit from FragmentPagerAdapter, but just from PagerAdapter.... and maybe it would be better to rename them as:
  MvxCachingPagerAdapter 
  MvxCachingStatePagerAdapter

Marco.

**Comment by nielscup** [comment]
I have the same doubts, additionally: the MvxCachingFragmentStatePagerAdapter is not usable this way because the constructor now needs `IEnumerable<FragmentInfo> fragments`. The whole point of a **State**PagerAdapter is that it is able to contain many pages which should be created in the adapter itself, instead of passing them into the constructor.

**Comment by Cheesebaron** [comment]
@nielscup they are created from the FragmentInfo. It contains enough information to inflate a View and attach a ViewModel to it.

**Comment by Cheesebaron** [comment]
Closing this as questions should be kept to StackOverflow, Slack or Xamarin Forums.
