### ISSUE TITLE
Create projects for each Xamarin Support Library

### ISSUE THREAD

**Issue by Dexyon** [MvvmCross/MvvmCross-AndroidSupport#3]
I would love to see a MvvmCross project for each Xamarin Support Library package that is out there. 

Namings would be:
- Cirrious.MvvmCross.Droid.Support.V4
- Cirrious.MvvmCross.Droid.Support.V7.LeanBack
- Cirrious.MvvmCross.Droid.Support.V7.Palette
- Cirrious.MvvmCross.Droid.Support.V7.*
- Cirrious.MvvmCross.Droid.Support.V13

**Comment by martijn00** [comment]
Good idea! I've updated pull-request #1 to have this naming.

**Comment by jamie94bc** [comment]
Do we _really_ need the version numbers in the project names and namespaces?

**Comment by martijn00** [comment]
I don't think we should have the version numbers. I think it would be best to use the naming that Xamarin gives the support packages, like: Cirrious.MvvmCross.Droid.Support.Appcompat

**Comment by jamie94bc** [comment]
Agreed, will update my original RecyclerView commit accordingly...

**Comment by Dexyon** [comment]
@martijn00 I like the fact that we try to use the naming that Xamarin gives to the support packages. However, Xamarin also included the version number: 
http://www.nuget.org/packages/Xamarin.Android.Support.v7.Palette/

There is also a reason why I would like to include the V number in the namespace. 
If you look at the V4, there are many other components included. 
http://developer.android.com/tools/support-library/features.html#v4

We should think of how we should do versioning compared to Google/Xamarin (22.1.1.1 is the latest right now). 

@Cheesebaron @slodge What are you opinions about this?

By the way. It also seems that other people are putting out nuget packages: 
http://www.nuget.org/packages/MvxAndroid.Support.V7/1.0.0-beta1

**Comment by jamie94bc** [comment]
The tricky part of versioning in line with Google/Xamarin is that we have two dependencies which may change. There may be some changes in MvvmCross which cause a change in the this library - how would we bump the version then?

**Comment by Dexyon** [comment]
@jamie94bc There are indeed two dependencies. I would like to follow the MvvmCross version numbering, such as all the plugins. 

E.G. When you look at the JSON plugin (which has a dependency on the Newtonsoft Json) is now at 3.5.1. When building a new version of our plugin, we should reference the latest stable versions of the dependency (matching MvvmCross and Xamarin.Android.Support via the packages.config).

https://github.com/MvvmCross/MvvmCross/blob/3.5/Plugins/Cirrious/Json/Cirrious.MvvmCross.Plugins.Json/packages.config.

When a user then wants a newer version of the Xamarin.Android.Support library it is up to the developer.

**Comment by martijn00** [comment]
All pull requests are now update to the correct name convention.
