### ISSUE TITLE
Rename Util project to Utils

### ISSUE THREAD

**Issue by martijn00** [MvvmCross/MvvmCross-AndroidSupport#313]
The Util project should be Utils to follow the convention Google made:
https://developer.android.com/topic/libraries/support-library/revisions.html#24-2-0-v4-refactor

We should rename assemblies, project names, put out a new nuget and unlist the old one.

**Comment by Cheesebaron** [comment]
There was a mismatch between assemblies and nugets so I just used lowest common denominator. Will fix this and push new nugets soon.

**Comment by Cheesebaron** [comment]
Is it on purpose that the single class inside of Utils uses the support.v4 namespace. Same goes for Fragments.

**Comment by martijn00** [comment]
Yes, this is on purpose. Google does the same thing. I am thinking they might make a breaking change for that some point in time.

**Comment by Cheesebaron** [comment]
I've uploaded new NuGets 4.4.1 to fix this.
