### ISSUE TITLE
Vector on background

### ISSUE THREAD

**Issue by penihel** [MvvmCross/MvvmCross-AndroidSupport#315]
HI.

I have problem similar as this #306 

But i'm using in a Button Background

### Steps to reproduce

1. Create a Vector (iconvoltar.xml)

2. Use it as button's background 

``` xml
<Button
        android:layout_width="16dp"
        android:layout_height="16dp"
        android:id="@+id/btnVoltar"
        android:background="@drawable/iconVoltar"
        android:elevation="0dp"
        android:shadowDy="0"
        android:shadowDx="0"
        android:shadowColor="#00ffffff" />

``` 

### Expected behavior
Show de vector

### Actual behavior
Error
Android.Content.Res.Resources+NotFoundException: File res/drawable/iconvoltar.xml from drawable resource ID #0x7f020066

### Configuration
Simple Android 4.4

**Version:** 4.4

**Comment by kjeremy** [comment]
Not an MvvmCross issue.  Use `app:srcCompat=`.
