### ISSUE TITLE
MvxFragment child state restore failure

### ISSUE THREAD

**Issue by JoeCooper** [MvvmCross/MvvmCross-AndroidSupport#48]
I found an odd quirk that might already be fixed in your tree but I'll report it here just in case. I am using MvvmCross 3.5.1 and Fragging 3.5.1 (though I also observed this in FullFragging).

Suppose I have a fragment like so:

```
[MvxOwnedViewModelFragment]
public class PointOfInterestView : MvxFragment<PointOfInterestViewModel>
{
    public override View OnCreateView (LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
    {           
        var ignore = base.OnCreateView(inflater, container, savedInstanceState); //warmup
        var view = this.BindingInflate (Resource.Layout.PointOfInterestView, container, false);
        return view;
    }
}
```

This is presented in an activity. If I minimize the app or otherwise cause it to lose state and reload, the ViewModel will not reload; the fragment will reappear anew with no VM bound.

However, if I add this code to the class:

```
public override void OnSaveInstanceState (Bundle outState)
{
    base.OnSaveInstanceState (outState);
    outState.PutInt ("hack", 0);
}
```

It works; the previous ViewModel is correctly attached to the new Fragment when the Activity is restored.

I thought this might involve reflection but if I remove the PutInt than it goes back to the unwanted behavior.

Is this a known issue? Is there another way I should be handling this?

**Comment by martijn00** [comment]
You need to use the MvxCachingFragmentActivity to fix this behaviour: https://github.com/MvvmCross/MvvmCross-AndroidSupport/blob/master/Cirrious.MvvmCross.Droid.Support.Fragging/MvxCachingFragmentActivity.cs

See this example how to implement that: https://github.com/MvvmCross/MvvmCross-AndroidSupport/tree/master/Samples

**Comment by JoeCooper** [comment]
Thanks for the reply.

I'm experimenting with it further. It seems that now I can't reproduce the problem with a top level fragment; using MvxFragmentActivity I can present an MvxFragment and it's perfectly happy to restore its state. (I had problems with this earlier this week and I'm not sure why I'm not seeing this problems now.) That MvxFragment cannot present a child fragment and restore its state without the hack, even if the root fragment is the caching activity.

Do I need some sort of caching fragment to present child fragments and restore their state? Should I make one, or some other strategy?

**Comment by martijn00** [comment]
Can this be related to https://github.com/MvvmCross/MvvmCross-AndroidSupport/issues/72 ? Did you have the json plugin installed?

**Comment by alexshikov** [comment]
This could be the fix https://github.com/MvvmCross/MvvmCross-AndroidSupport/commit/98358cb40ff406b35829e23dff9dcc1c31bb583e

**Comment by thefex** [comment]
Please close that, it's fixed as @SeeD-Seifer mentioned
