### ISSUE TITLE
Lack of JNI Constructor... Is it needed?

### ISSUE THREAD

**Issue by IlSocio** [MvvmCross/MvvmCross-AndroidSupport#54]
Both the MvxCachingFragmentActivityCompat and the MvxEventSourceAppCompatActivity are currently missing the constructor (IntPtr javaReference, JniHandleOwnership transfer)
Since, it is not totally clear to me the purpose of this constructor, I'm wondering if the lack of this JNI constructor is intentional, or it should be added...
More in general, should we always expose the JNI constructor of the base class?

https://github.com/MvvmCross/MvvmCross-AndroidSupport/blob/master/Cirrious.MvvmCross.Droid.Support.AppCompat/MvxCachingFragmentActivityCompat.cs
https://github.com/MvvmCross/MvvmCross-AndroidSupport/blob/master/Cirrious.MvvmCross.Droid.Support.AppCompat/MvxEventSourceAppCompatActivity.cs

**Comment by martijn00** [comment]
Thanks for notifing. I've addessed this in https://github.com/MvvmCross/MvvmCross-AndroidSupport/pull/56
