### ISSUE TITLE
Issue with MvxImageView inside MvxRecyclerView

### ISSUE THREAD

**Issue by jbolle** [MvvmCross/MvvmCross-AndroidSupport#64]
Hello,

I have an issue with the display of MvxImageViews when they're inside a MvxRecyclerView. 

I really don't know if it's related to DownloadCache plugin, MvxImageView component or MvxRecyclerView but it seems on the first display, some images don't appear but after some recycles of the RecyclerView by playing with the scroll, all images finally display.

I'm using 4.0.0-beta2 version of MvvmCross and I made a sample to reproduce the issue starting with an example found in MvvmCross-AndroidSupport. 

My sample is available here : https://github.com/jbolle/MvxImgView-Issue

Thanks for your help.

**Comment by jbrunpicard** [comment]
Hi,

Same problem here.
Have to request for layout or any screen action to make images appear.
Maybe something around async loading process of images.

**Comment by Cheesebaron** [comment]
I will investigate it tomorrow and see if I can find out what is going on. Thanks for the repro sample :+1:

**Comment by cyrilcathala** [comment]
I think I found the problem: loading the image is async, so if the view is recycled before the image is loaded, it causes the problem.

I need to test it more, but a quick fix might be in the MvxImageView:

``` csharp
private Bitmap _image;

private async void ImageHelperOnImageChanged (object sender, MvxValueEventArgs<Bitmap> mvxValueEventArgs)
{
    _image = mvxValueEventArgs.Value;

    Post (() => { // marshal back on UI Thread
        try {
            SetImageBitmap (_image);
        } catch (Exception ex) {
            Mvx.Error (ex.Message);
        }
    });
}
```

**Comment by hugoparis19** [comment]
Hi,
I try the fix but when the list refresh, the image disappear.

**Comment by clintonrocksmith** [comment]
This was also a problem for me with MvxListView as well.  I might have a look at it to move the next version along.

**Comment by martijn00** [comment]
There where some updates on this in MvxImageView. Do you guys still experience this problem?
