### ISSUE TITLE
Tab page title lost after navigating to different fragment

### ISSUE THREAD

**Issue by binoypatel** [MvvmCross/MvvmCross-AndroidSupport#66]
Hi

When navigating to Settings and then navigating (either using back button or from navigation panel) to Home, it is not showing Tab page title (ie. RecycleView).

Not sure how to fix this?

Thanks,
Binoy
![capture](https://cloud.githubusercontent.com/assets/4742252/9723327/bc868334-558c-11e5-9c91-235f550440b6.PNG)

**Comment by Cheesebaron** [comment]
As question is now there is not enough information to reproduce your issue, nor is it not clear whether it is a MvvmCross issue or just PEBCAK.

Make a reproducible sample if you believe this is a MvvmCross issue, otherwise use StackOverflow non-MvvmCross issues, but problems with usage.

Reopen when you have something to reproduce.

**Comment by binoypatel** [comment]
Not sure why you cannot reproduce the issue. Anyway, here are the steps to reproduce the issue:
- Run Example.Droid
- It will navigate to ExamplesFragment and will show RecyclerViewFragment with the Tab page title "RECYCLERVIEW" (Refer Image01.png)
- Navigate to Settings Fragment (Refer Image02.png)
- Navigate to Home (either using back button or navigation menu)
- Notice the Tab page title is blank (refer Image03.png)

![image01](https://cloud.githubusercontent.com/assets/4742252/9764256/17ecacbc-56dc-11e5-9e84-0812bfc53f66.PNG)
![image02](https://cloud.githubusercontent.com/assets/4742252/9764258/17f00858-56dc-11e5-83a8-8e31cb451bcd.PNG)
![image03](https://cloud.githubusercontent.com/assets/4742252/9764257/17ef06ba-56dc-11e5-84cd-940bcea85714.png)

**Comment by Cheesebaron** [comment]
[**@binoypatel**](https://github.com/binoypatel) commented on [Sep 9, 2015, 4:22 PM GMT+2](https://github.com/MvvmCross/MvvmCross-AndroidSupport/issues/66#issuecomment-138925030):

> Not sure why you cannot reproduce the issue.

Basically the steps of reproduction were missing, which you have provided now. I don't have telepathic superpowers so I can read your mind.

Thanks for the steps of reproduction, someone sometime will probably take a look.

**Comment by binoypatel** [comment]
Understood :)

**Comment by martijn00** [comment]
I've looked at the issue, and can confirm that this indeed is happening in the sample. Couldn't find a fix yet, but this doesn't seem to happen in our own app where we use the same construction. I will look into fixing this when i have time.

**Comment by jamsoft** [comment]
Just for what it's worth I see this issue in the Example Project and my own project based on the sample.

**Comment by jamsoft** [comment]
Martijn00 The only thing I can think of is that in your real app where it's working something else must be happening to force a "repaint" of some description.

I wonder if it might be something in the measure pass of all the UI elements?  I'm completely shooting in the dark though.

**Comment by martijn00** [comment]
Yes i was thinking it should be something like that, but i couldn't discover anything.

**Comment by martijn00** [comment]
Can't reproduce this in the latest samples. Please reopen if still applicable.
