### ISSUE TITLE
Sample fails with NullReferenceException when rotating screen

### ISSUE THREAD

**Issue by mattwhetton** [MvvmCross/MvvmCross-AndroidSupport#72]
The sample provided throws a null reference exception whenever you rotate the screen (i.e. enter save/restore state cycle). 

It seems to be thrown in the RestoreLookupFromSleep method of the MvxCachingFragmentActivity as the SupportFragmentManager.Fragments is null.

The wider implication is that the save/restore state cycle does not work.

**Comment by martijn00** [comment]
Fixed in #73
