### ISSUE TITLE
Add NavigationView bindings

### ISSUE THREAD

**Issue by martijn00** [MvvmCross/MvvmCross-AndroidSupport#74]
After comment of @vvolkgang 

Was thinking about that, if it made sense to keep the current Core menu strategy (binded MenuItem) and enhance it with the new NavigationView stuff (sub menus for instance). My current position is that it doesn't, any "crossplatform" solution would be Droid first and all of the other platforms would have to adapt to that. Furthermore, you would sacrifice some "ease" of development in Droid (for instance, being able to refer to menu items in a type-safe-ish way, which is great for some L10N implementations). That being said, having the MenuVM with one or multiple MvxCommands being triggered by the platform seems to be the best compromise.

Some thoughts in Jabbr from @martijn00

This would require some good thinking on the solution, think of support for images / icons in the navigation view, with multi platform support. Maybe a multi level collection and a value converter would help, and off course bindings for the navigation viewer.

**Comment by vvolkgang** [comment]
Due to current native ease of development to support subcategories + icons + localization, I scratched this idea but, what I had in mind was:
1. One PCL model similar to this:

``` csharp
public class MenuItem
{
    string Icon;
    string Title;
    string SubCategory;
    Type GoToViewModdel;
}
```
1. `MenuViewModel` with `ObservableCollection<MenuItem>` and one `MvxCommand<MenuItem>`
2. Binding would automagically add each menu item to it's SubCategory, if null, add it to the main one

**Comment by martijn00** [comment]
Maybe it would be an idea to only bind the click action of the menu items. The problem then would be how you know what item was clicked in the command.

**Comment by vvolkgang** [comment]
You could only send the title to the PCL. Thats crazy to deal with if you add L10N, specially when the platform is already giving you ID's to work with, like you did in the [Android sample](https://github.com/MvvmCross/MvvmCross-AndroidSupport/blob/master/Samples/Example.Droid/Fragments/MenuFragment.cs#L48).
