### ISSUE TITLE
Difference between MvxAppCompatActivity vs MvxFragmentCompatActivity

### ISSUE THREAD

**Issue by IlSocio** [MvvmCross/MvvmCross-AndroidSupport#75]
I'm wondering... what's the difference between these two classes:
https://github.com/MvvmCross/MvvmCross-AndroidSupport/blob/2b24c360a7ea05ed1e57f02d5a11a72fa0477e86/Cirrious.MvvmCross.Droid.Support.AppCompat/MvxAppCompatActivity.cs
https://github.com/MvvmCross/MvvmCross-AndroidSupport/blob/2b24c360a7ea05ed1e57f02d5a11a72fa0477e86/Cirrious.MvvmCross.Droid.Support.AppCompat/MvxFragmentCompatActivity.cs

It seems to me that they do exactly the same stuff... 
Maybe, one of these should be removed to avoid confusion?

Another question... 
Shouldn't the MvxAppCompatActivity call the jni constructor, like in the MvxFragmentCompatActivity?

And the last one: 
Shouldn't the MvxFragmentCompatActivity call the MvxAppCompatActivityHelper too, like in the MvxAppCompatActivity?

**Comment by martijn00** [comment]
Good questions! I think we could remove `MvxFragmentCompatActivity` and add the jni ctor to the `MvxAppCompatActivity`. That would solve everything.
