### ISSUE TITLE
Improve `MvxCachingFragmentActivity.RegisterFragment` to deal with Backstack and Transitions on the registry level

### ISSUE THREAD

**Issue by vvolkgang** [MvvmCross/MvvmCross-AndroidSupport#77]
Giving that one already needs to manually register the fragments, this mechanism can be improved to enable devs to set transitions and if that fragment should clear the backstack.

This information should be added to the `FragmentInfo` config file and then used in `ShowFragment`.

Regarding the transitions, [following this implementation](https://github.com/steffkelsey/Xamarin_MvvmCross_MaterialDesign/blob/master/MvxMaterial.DroidFullFrag/MainActivity.cs#L110), we only need something like a `FragmentTransitionInfo` with nullable ints for all of the possible transitions, if set, they'll be inflated when a new fragment is created.

This will reduce the code complexity required to implement something like the `Home/MainActivity` with a drawer.

**Comment by martijn00** [comment]
Not sure if it is a good idea to add all those things to a new Info class. We probably should try to keep this as native as possible, so maybe it would be better to expose some methods you could override to do this?

**Comment by vvolkgang** [comment]
I addressed this in #86. Inheritors can now create their custom `IMvxCachedFragmentInfo` to address scenarios such as transitions. Added more callbacks to enable that type of customization. 

Furthermore, added `AddToBackStack` to that interface + base implementation so it can be done by default, `ShowFragment` now asks for `forceAddToBackStack` instead.
