### ISSUE TITLE
Fragging vs Full Fragging

### ISSUE THREAD

**Issue by vvolkgang** [MvvmCross/MvvmCross-AndroidSupport#78]
Apart from some refactoring, whats the diff between Fraggin (here) and Full Fragging in the main Mvx repo?

Main features seem to be in sync, are we supposed to improve both implementations?

**Comment by martijn00** [comment]
The support repo is build on the base classes of the Android Support libraries. The full fragging repo uses the native fragments which are available after Android 3.2.

For now we should indeed keep those in sync. We have an issue open https://github.com/MvvmCross/MvvmCross/issues/1124 that could improve this.
