### ISSUE TITLE
Automate register Bindings of AppCompat classes

### ISSUE THREAD

**Issue by jeremy-alley** [MvvmCross/MvvmCross-AndroidSupport#80]
I get the following warning when using MvxSpinner and the SelectedItem is not selected.

MvxBind:Warning: 5.40 Failed to create target binding for binding SelectedItem for SelectedColor

This is in reference to this stackoverflow post:
http://stackoverflow.com/questions/32718037/issue-binding-to-mvxspinner-after-upgrading-to-mvvmcross-v4-0-0-beta3

**Comment by martijn00** [comment]
@kjeremy do you have idea's on this one?

**Comment by kjeremy** [comment]
@martijn00  You'll need to call `MvxAppCompatSetupHelper.FillTargetFactories` from your `Setup.cs`.  Maybe there's a way we can automate that via the plugin architecture?

**Comment by jeremy-alley** [comment]
Thanks for the help @martijn00  and @kjeremy!

**Comment by martijn00** [comment]
Fixed via https://github.com/MvvmCross/MvvmCross-AndroidSupport/pull/238
