### ISSUE TITLE
Automate calling `MvxAppCompatSetupHelper.FillTargetFactories` from Setup.cs

### ISSUE THREAD

**Issue by kjeremy** [MvvmCross/MvvmCross-AndroidSupport#82]
We need to figure out how to either automatically call `MvxAppCompatSetupHelper.FillTargetFactories` from the user''s overriden `MvxAndroidSetup.FillTargetFactories` when MvvmCross-AndroidSupport is installed or document it in the `README.md`.

See #80

**Comment by vvolkgang** [comment]
I just hit this face first, really cumbersome. What do you think about having a `MvxAndroidAppCompatSetup` that handles not only that, but also the custom `AppCompatViewFactory`  and possibly `AndroidViewAssemblies` if required?

**Comment by kjeremy** [comment]
As long as we can still override everything I think that's reasonable.
