### ISSUE TITLE
MvxCachingFragmentActivity prevents going back to other activies

### ISSUE THREAD

**Issue by vvolkgang** [MvvmCross/MvvmCross-AndroidSupport#94]
If theres only one fragment in the activity and the user presses back, the app is sent to background. This prevents scenarios where you have a previous activity.

[This line](https://github.com/MvvmCross/MvvmCross-AndroidSupport/blob/master/Cirrious.MvvmCross.Droid.Support.Fragging/MvxCachingFragmentActivity.cs#L308) needs to go. In that case, should we just clean the `SupportFragmentManager` and run the base implementation?

**Comment by martijn00** [comment]
I think running the base will do.

**Comment by vvolkgang** [comment]
@martijn00 it will run `Activity.OnBackPressed()`, the Fragment instance will be retained in the `SupportFragmentManager` and `MvxCachingFragmentActivity` tracking structures. 
1. Do you know when will the instance of the `MvxCachingFragmentActivity` and `ViewModel` are cleaned? 
2. If you re-open a previously closed `MvxCachingFragmentActivity` is there any change or configuration that might use the old instance, or a new one will be created regardless?

I'm afraid of a memory leak in this process.

**Comment by vvolkgang** [comment]
So, poping the backstack was required anw. `AppCompatActivity` extends `FragmentActivity`, the first `base.OnBackButtonPressed` will then pop the backstack first.
